language: python
sudo: false
dist: bionic
matrix:
  fast_finish: true
  include:
      - python: "2.7"
        env: TOXENV=py27-Plone51,py27-Plone52
      - python: "3.7"
        env: TOXENV=py37-Plone52
install:
  - pip install tox
script:
  - tox
cache:
  pip: true
  directories:
    - eggs/
